# Generated by Django 5.1.7 on 2025-04-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('disco', models.CharField(max_length=50)),
            ],
        ),
    ]
