# Generated by Django 5.1.7 on 2025-04-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='marca',
            new_name='mouse',
        ),
        migrations.RenameField(
            model_name='computador',
            old_name='nombre',
            new_name='pantalla',
        ),
        migrations.RenameField(
            model_name='computador',
            old_name='procesador',
            new_name='software',
        ),
        migrations.RenameField(
            model_name='computador',
            old_name='referencia',
            new_name='teclado',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='disco',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='ram',
        ),
    ]
